# Experimental Evaluation — feedback-cycle aware

This notebook evaluates the thesis extension **using all the outputs produced by the bottom-up feedback cycle**, not only the final standalone JSON.

It keeps the paper-aligned semantic evaluation for **High-Level Goals (HLG)** and **Low-Level Goals (LLG)**:

1. the original goal-text preprocessing used by `GoalEvaluator`;
2. BERT embeddings (`bert-base-uncased`);
3. cosine similarity between generated and ground-truth goals;
4. maximum-weight one-to-one bipartite matching (Hungarian assignment);
5. **Precision, Recall and F1-score**.

In addition, the notebook consumes the per-iteration outputs:

- `iteration_XXX_global_evaluations*.json`;
- `iteration_XXX_documentation_coverage*.json` when present;
- the complete `globalGoalCycle.iterations` history in the standalone JSON.

This distinction is important for failed/non-converged runs. The standalone file can roll back `final_*` to the last fully validated state, while the iteration files still contain the states that were actually evaluated during the feedback loop. Therefore the notebook reports separately:

- **Returned state**: what the orchestrator finally returned;
- **Evaluated trajectory**: the complete HLG/LLG state entering every iteration;
- **Latest candidate**: the latest candidate recorded by the cycle, explicitly marked as non-converged when appropriate;
- **Evaluator/coverage diagnostics**: branch decisions and documentation gaps from the uploaded iteration JSONs.

Actors are not evaluated because the thesis extension does not modify actor extraction.


This revision also exports cardinality/proliferation indicators, detailed Hungarian assignments, ground-truth recovery trajectories, semantic-duplicate diagnostics, and actor-level branch diagnostics. Diagnostic thresholds are kept separate from the paper-aligned Precision/Recall/F1 computation.

In [ ]:
from pathlib import Path
import json
import os
import re
import socket
import sys
from collections import Counter

# Fail faster on unavailable Hugging Face connections instead of retrying silently.
os.environ.setdefault("HF_HUB_ETAG_TIMEOUT", "30")
os.environ.setdefault("HF_HUB_DOWNLOAD_TIMEOUT", "60")

import nltk
import numpy as np
import pandas as pd
import torch
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from scipy.optimize import linear_sum_assignment
from tqdm.auto import tqdm
from transformers import AutoModel, AutoTokenizer

# ------------------------------------------------------------
# Project discovery
# ------------------------------------------------------------
CWD = Path.cwd().resolve()
PROJECT_ROOT = next((p for p in (CWD, CWD.parent) if (p / "src").exists()), CWD)
NOTEBOOK_DIR = PROJECT_ROOT / "notebook"
OUTPUT_DIR = PROJECT_ROOT / "output"

for path in (PROJECT_ROOT, NOTEBOOK_DIR, CWD):
    if path.exists() and str(path) not in sys.path:
        sys.path.insert(0, str(path))

from groundtruth import SIA_PROJECT_25_26

RUN_LABEL = "SIA Project 25 26_FEW_SHOT"

# Optional manual overrides. Leave as None/empty for auto-discovery.
RUN_PATH_OVERRIDE = None
GLOBAL_EVAL_PATH_OVERRIDES = []
DOC_COVERAGE_PATH_OVERRIDES = []

EVALUATION_DIR = OUTPUT_DIR / "evaluation" / RUN_LABEL
EVALUATION_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Evaluation output:", EVALUATION_DIR)

# ------------------------------------------------------------
# NLTK resources: check first; download only if really missing.
# ------------------------------------------------------------
NLTK_RESOURCES = {
    "punkt": ("tokenizers/punkt",),
    "punkt_tab": ("tokenizers/punkt_tab",),
    "wordnet": ("corpora/wordnet", "corpora/wordnet.zip"),
    "omw-1.4": ("corpora/omw-1.4", "corpora/omw-1.4.zip"),
    "stopwords": ("corpora/stopwords",),
}

def _resource_exists(candidates):
    for candidate in candidates:
        try:
            nltk.data.find(candidate)
            return True
        except LookupError:
            pass
    return False

previous_timeout = socket.getdefaulttimeout()
socket.setdefaulttimeout(45)
try:
    for package, candidates in NLTK_RESOURCES.items():
        if not _resource_exists(candidates):
            print(f"Downloading missing NLTK resource: {package}")
            ok = nltk.download(package, quiet=False, raise_on_error=False)
            if not ok:
                raise RuntimeError(
                    f"Could not download NLTK resource '{package}'. "
                    "Check the network once, then rerun this cell."
                )
finally:
    socket.setdefaulttimeout(previous_timeout)

print("NLTK resources ready.")

Project root: C:\Users\agnes_lryeu3v\Desktop\tesi
Evaluation output: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama
NLTK resources ready.

## 1. Load the standalone run and the per-iteration outputs

The external iteration files are treated as audit outputs. When an external file is not found, the notebook falls back to the copy embedded in the standalone cycle history and reports that fallback explicitly.

In [16]:
def newest(paths):
    existing = [Path(p) for p in paths if Path(p).exists()]
    return max(existing, key=lambda p: p.stat().st_mtime) if existing else None


def discover_run_path() -> Path:
    if RUN_PATH_OVERRIDE is not None:
        path = Path(RUN_PATH_OVERRIDE)
        if not path.exists():
            raise FileNotFoundError(path)
        return path

    roots = [CWD, NOTEBOOK_DIR, OUTPUT_DIR, CWD / "output", CWD.parent / "output"]
    candidates = []
    pattern = f"{RUN_LABEL}_bottom_up_standalone*.json"
    for root in roots:
        if root.exists():
            candidates.extend(root.glob(pattern))
            candidates.extend(root.rglob(pattern))

    # De-duplicate paths before taking the newest file.
    candidates = list(dict.fromkeys(p.resolve() for p in candidates))
    path = newest(candidates)
    if path is None:
        raise FileNotFoundError(
            "Feedback-cycle standalone JSON not found. Set RUN_PATH_OVERRIDE in the configuration cell."
        )
    return path


RUN_PATH = discover_run_path()
with RUN_PATH.open("r", encoding="utf-8") as f:
    run_data = json.load(f)

cycle = run_data["globalGoalCycle"]
iterations = sorted(cycle.get("iterations", []) or [], key=lambda it: int(it.get("iteration", 0)))

if not iterations:
    raise RuntimeError("The cycle JSON contains no iterations.")

print("Run:", RUN_PATH)
print("Cycle converged:", bool(cycle.get("converged")))
print("Stop reason:", cycle.get("stop_reason"))
print("Completed iterations:", cycle.get("completed_iterations", len(iterations)))


ITER_RE = re.compile(r"iteration_(\d+)_", re.IGNORECASE)


def iteration_number_from_path(path: Path):
    m = ITER_RE.search(path.name)
    return int(m.group(1)) if m else None


def candidate_search_roots():
    roots = [RUN_PATH.parent, CWD, NOTEBOOK_DIR, OUTPUT_DIR]

    # The standalone may contain an output directory created on another machine.
    # Use it only if that path exists in the current environment.
    recorded = run_data.get("evaluation_output_directory")
    if recorded:
        p = Path(recorded)
        if p.exists():
            roots.append(p)

    return list(dict.fromkeys(p.resolve() for p in roots if p.exists()))


def discover_iteration_files(kind: str, overrides=None):
    overrides = overrides or []
    if overrides:
        paths = [Path(p) for p in overrides]
        missing = [p for p in paths if not p.exists()]
        if missing:
            raise FileNotFoundError(f"Missing override files: {missing}")
    else:
        if kind == "global":
            pattern = "iteration_*_global_evaluations*.json"
        elif kind == "coverage":
            pattern = "iteration_*_documentation_coverage*.json"
        else:
            raise ValueError(kind)

        paths = []
        for root in candidate_search_roots():
            paths.extend(root.glob(pattern))
            paths.extend(root.rglob(pattern))
        paths = list(dict.fromkeys(p.resolve() for p in paths))

    # If several versions exist for one iteration, keep the newest one.
    by_iteration = {}
    for p in paths:
        n = iteration_number_from_path(p)
        if n is None:
            continue
        current = by_iteration.get(n)
        if current is None or p.stat().st_mtime > current.stat().st_mtime:
            by_iteration[n] = p
    return dict(sorted(by_iteration.items()))


GLOBAL_EVAL_FILES = discover_iteration_files("global", GLOBAL_EVAL_PATH_OVERRIDES)
DOC_COVERAGE_FILES = discover_iteration_files("coverage", DOC_COVERAGE_PATH_OVERRIDES)


def load_json(path):
    with Path(path).open("r", encoding="utf-8") as f:
        return json.load(f)


external_global = {i: load_json(p) for i, p in GLOBAL_EVAL_FILES.items()}
external_coverage = {i: load_json(p) for i, p in DOC_COVERAGE_FILES.items()}
embedded_iterations = {int(it.get("iteration", 0)): it for it in iterations}

# Canonical audit data: external JSON when available, embedded copy otherwise.
GLOBAL_AUDIT = {}
COVERAGE_AUDIT = {}
AUDIT_SOURCE = {}

for i, it in embedded_iterations.items():
    if i in external_global:
        GLOBAL_AUDIT[i] = external_global[i]
        AUDIT_SOURCE[(i, "global")] = str(GLOBAL_EVAL_FILES[i])
    else:
        GLOBAL_AUDIT[i] = {
            "status": "EMBEDDED_FALLBACK",
            "expected_branch_ids": list((it.get("global_evaluations") or {}).keys()),
            "evaluated_branch_ids": list((it.get("global_evaluations") or {}).keys()),
            "missing_branch_ids": [],
            "unexpected_branch_ids": [],
            "inconsistent_branch_ids": [],
            "evaluations": it.get("global_evaluations") or {},
            "errors": it.get("global_evaluation_errors") or {},
        }
        AUDIT_SOURCE[(i, "global")] = "embedded in standalone"

    if i in external_coverage:
        COVERAGE_AUDIT[i] = external_coverage[i]
        AUDIT_SOURCE[(i, "coverage")] = str(DOC_COVERAGE_FILES[i])
    elif it.get("documentation_coverage") is not None:
        COVERAGE_AUDIT[i] = {
            "status": "EMBEDDED_FALLBACK",
            "documentation_coverage": it.get("documentation_coverage"),
        }
        AUDIT_SOURCE[(i, "coverage")] = "embedded in standalone"

print("\nPer-iteration audit files considered:")
for i in sorted(embedded_iterations):
    print(f"Iteration {i} global evaluator: {AUDIT_SOURCE.get((i, 'global'))}")
    if (i, "coverage") in AUDIT_SOURCE:
        print(f"Iteration {i} documentation coverage: {AUDIT_SOURCE[(i, 'coverage')]}")

Run: C:\Users\agnes_lryeu3v\Desktop\tesi\output\SIA Project 25 26_FEW_SHOT_noLlama_bottom_up_standalone.json
Cycle converged: False
Stop reason: MAX_ITERATIONS_REACHED
Completed iterations: 5

Per-iteration audit files considered:
Iteration 1 global evaluator: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_FEW_SHOT_noLlama\iteration_001_global_evaluations.json
Iteration 1 documentation coverage: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_ONE_SHOT\iteration_001_documentation_coverage.json
Iteration 2 global evaluator: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_FEW_SHOT_noLlama\iteration_002_global_evaluations.json
Iteration 2 documentation coverage: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_FEW_SHOT_noLlama\iteration_002_documentation_coverage.json
Iteration 3 global evaluator: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_FEW_SHOT_noLlama\iteration_003_global_evaluations.json
Iteration 4 global evaluator: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_FEW_SHOT_noLlama\iteration_004_global_evaluations.json
Iteration 4 documentation coverage: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_ONE_SHOT\iteration_004_documentation_coverage.json
Iteration 5 global evaluator: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_FEW_SHOT_noLlama\iteration_005_global_evaluations.json
Iteration 5 documentation coverage: C:\Users\agnes_lryeu3v\Desktop\tesi\output\bottom_up_iterations\SIA Project 25 26_FEW_SHOT_noLlama\iteration_005_documentation_coverage.json

## 2. Build comparable goal states

For the iteration trajectory, the notebook evaluates the **input state of each iteration**. This is deliberate: that is the complete HLG/LLG state actually inspected by the corresponding `global_evaluations` file. It avoids treating a failed regeneration as if it had produced an empty goal set.

In [17]:
REFERENCE_HLG = [str(x).strip() for x in SIA_PROJECT_25_26["highLevelGoals"] if str(x).strip()]
REFERENCE_LLG = [str(x).strip() for x in SIA_PROJECT_25_26["lowLevelGoals"] if str(x).strip()]

GENERIC_GOAL_ID = re.compile(r"^(?:HLG|LLG|BRANCH)(?:[_\- ]?\d+)?$", re.IGNORECASE)


def goal_text(item) -> str:
    if item is None:
        return ""
    if isinstance(item, str):
        return item.strip()
    if not isinstance(item, dict):
        return str(item).strip()

    description = item.get("description")
    if isinstance(description, str) and description.strip():
        return description.strip()

    name = item.get("name")
    if isinstance(name, str) and name.strip() and not GENERIC_GOAL_ID.fullmatch(name.strip()):
        return name.strip()

    return ""


def extract_hlg(container) -> list[str]:
    if container is None:
        return []
    items = container.get("goals", []) if isinstance(container, dict) else container
    return [text for item in items if (text := goal_text(item))]


def extract_llg(container) -> list[str]:
    if container is None:
        return []
    items = container.get("low_level_goals", []) if isinstance(container, dict) else container
    return [text for item in items if (text := goal_text(item))]


# The state entering each iteration is the state evaluated by that iteration's global evaluator.
ITERATION_STATES = []
for it in iterations:
    i = int(it.get("iteration", 0))
    hlg = extract_hlg(it.get("input_high_level_goals"))
    llg = extract_llg(it.get("input_low_level_goals"))
    ITERATION_STATES.append({"iteration": i, "hlg": hlg, "llg": llg})

BASELINE_HLG = ITERATION_STATES[0]["hlg"]
BASELINE_LLG = ITERATION_STATES[0]["llg"]

RETURNED_HLG = extract_hlg(run_data.get("finalHighLevelGoals") or cycle.get("final_high_level_goals"))
RETURNED_LLG = extract_llg(run_data.get("finalLowLevelGoals") or cycle.get("final_low_level_goals"))

BEST_VALIDATED_HLG = extract_hlg(cycle.get("best_validated_high_level_goals"))
BEST_VALIDATED_LLG = extract_llg(cycle.get("best_validated_low_level_goals"))

LAST_CANDIDATE_HLG = extract_hlg(cycle.get("last_candidate_high_level_goals"))
LAST_CANDIDATE_LLG = extract_llg(cycle.get("last_candidate_low_level_goals"))

print(f"Ground truth:       HLG={len(REFERENCE_HLG)}, LLG={len(REFERENCE_LLG)}")
print(f"Baseline:           HLG={len(BASELINE_HLG)}, LLG={len(BASELINE_LLG)}")
for state in ITERATION_STATES:
    print(f"Iteration {state['iteration']} input: HLG={len(state['hlg'])}, LLG={len(state['llg'])}")
print(f"Best validated:     HLG={len(BEST_VALIDATED_HLG)}, LLG={len(BEST_VALIDATED_LLG)}")
print(f"Returned state:     HLG={len(RETURNED_HLG)}, LLG={len(RETURNED_LLG)}")
print(f"Latest candidate:   HLG={len(LAST_CANDIDATE_HLG)}, LLG={len(LAST_CANDIDATE_LLG)}")

if not cycle.get("converged"):
    print("\nIMPORTANT: the cycle did not converge. Latest-candidate metrics are diagnostic, not a final successful-cycle result.")

Ground truth:       HLG=9, LLG=21
Baseline:           HLG=5, LLG=12
Iteration 1 input: HLG=5, LLG=12
Iteration 2 input: HLG=5, LLG=12
Iteration 3 input: HLG=5, LLG=16
Iteration 4 input: HLG=5, LLG=14
Iteration 5 input: HLG=5, LLG=19
Best validated:     HLG=0, LLG=0
Returned state:     HLG=9, LLG=28
Latest candidate:   HLG=9, LLG=28

IMPORTANT: the cycle did not converge. Latest-candidate metrics are diagnostic, not a final successful-cycle result.

## 3. Per-iteration evaluator and documentation-coverage diagnostics

These values come from the uploaded iteration outputs when available. They are separate from BERT Precision/Recall/F1: they describe **what the feedback loop decided and why it continued**.

In [18]:
def coverage_payload(audit):
    if not audit:
        return None
    return audit.get("documentation_coverage") if "documentation_coverage" in audit else audit


diagnostic_rows = []
for state in ITERATION_STATES:
    i = state["iteration"]
    g = GLOBAL_AUDIT.get(i, {})
    evaluations = g.get("evaluations") or {}
    decisions = Counter(v.get("decision", "UNKNOWN") for v in evaluations.values())

    cov = coverage_payload(COVERAGE_AUDIT.get(i))
    cov_status = cov.get("status") if cov else None
    missing_hlg = len(cov.get("missing_high_level_goals", []) or []) if cov else 0
    generation_requests = len(cov.get("generation_requests", []) or []) if cov else 0

    diagnostic_rows.append({
        "iteration": i,
        "hlg_count": len(state["hlg"]),
        "llg_count": len(state["llg"]),
        "expected_branches": len(g.get("expected_branch_ids", []) or []),
        "evaluated_branches": len(g.get("evaluated_branch_ids", []) or []),
        "missing_branches": len(g.get("missing_branch_ids", []) or []),
        "unexpected_branches": len(g.get("unexpected_branch_ids", []) or []),
        "inconsistent_branches": len(g.get("inconsistent_branch_ids", []) or []),
        "confirm_branch": decisions.get("CONFIRM_BRANCH", 0),
        "matches_other_hlg": decisions.get("MATCHES_OTHER_HIGH_LEVEL_GOAL", 0),
        "other_decisions": sum(v for k, v in decisions.items() if k not in {"CONFIRM_BRANCH", "MATCHES_OTHER_HIGH_LEVEL_GOAL"}),
        "requires_hlg_regeneration": sum(bool(v.get("requires_high_level_regeneration")) for v in evaluations.values()),
        "requires_llg_regeneration": sum(bool(v.get("requires_low_level_regeneration")) for v in evaluations.values()),
        "global_evaluation_errors": len(g.get("errors", {}) or {}),
        "documentation_status": cov_status,
        "missing_documentation_hlg": missing_hlg,
        "documentation_generation_requests": generation_requests,
        "global_source": AUDIT_SOURCE.get((i, "global")),
        "coverage_source": AUDIT_SOURCE.get((i, "coverage")),
    })

diagnostics_df = pd.DataFrame(diagnostic_rows)
display(diagnostics_df)

print("\nNon-CONFIRM decisions:")
for i in sorted(GLOBAL_AUDIT):
    for branch_id, ev in (GLOBAL_AUDIT[i].get("evaluations") or {}).items():
        if ev.get("decision") != "CONFIRM_BRANCH":
            matched = (ev.get("matched_high_level_goal") or {}).get("name")
            print(
                f"Iteration {i} - {branch_id}: {ev.get('decision')} | "
                f"matched={matched!r} | requires LLG regeneration={ev.get('requires_low_level_regeneration')}"
            )

print("\nDocumentation gaps:")
for i in sorted(COVERAGE_AUDIT):
    cov = coverage_payload(COVERAGE_AUDIT[i])
    for item in cov.get("missing_high_level_goals", []) or []:
        actor = (item.get("actor") or {}).get("name")
        print(f"Iteration {i} - actor={actor!r} - evidence={item.get('source_evidence')}")

,iteration,hlg_count,llg_count,expected_branches,evaluated_branches,missing_branches,unexpected_branches,inconsistent_branches,confirm_branch,matches_other_hlg,other_decisions,requires_hlg_regeneration,requires_llg_regeneration,global_evaluation_errors,documentation_status,missing_documentation_hlg,documentation_generation_requests,global_source,coverage_source
0,1,5,12,5,5,0,0,0,2,0,3,3,3,0,MISSING_HIGH_LEVEL_GOALS,2,2,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...
1,2,5,12,5,5,0,0,0,4,0,1,1,1,0,MISSING_HIGH_LEVEL_GOALS,2,0,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...
2,3,5,16,5,5,0,0,0,3,0,2,2,2,0,NaN,0,0,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...,NaN
3,4,5,14,5,5,0,0,0,4,0,1,1,1,0,MISSING_HIGH_LEVEL_GOALS,1,1,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...
4,5,5,19,5,5,0,0,0,5,0,0,0,0,0,MISSING_HIGH_LEVEL_GOALS,5,5,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...,C:\Users\agnes_lryeu3v\Desktop\tesi\output\bot...

Non-CONFIRM decisions:
Iteration 1 - branch_003: REGENERATE_HIGH_LEVEL_GOAL | matched=None | requires LLG regeneration=True
Iteration 1 - branch_004: REGENERATE_HIGH_LEVEL_GOAL | matched=None | requires LLG regeneration=True
Iteration 1 - branch_005: REGENERATE_HIGH_LEVEL_GOAL | matched=None | requires LLG regeneration=True
Iteration 2 - branch_003: REGENERATE_HIGH_LEVEL_GOAL | matched=None | requires LLG regeneration=True
Iteration 3 - branch_003: REGENERATE_HIGH_LEVEL_GOAL | matched=None | requires LLG regeneration=True
Iteration 3 - branch_004: REGENERATE_HIGH_LEVEL_GOAL | matched=None | requires LLG regeneration=True
Iteration 4 - branch_002: REGENERATE_HIGH_LEVEL_GOAL | matched=None | requires LLG regeneration=True

Documentation gaps:
Iteration 1 - actor='Public' - evidence=Section D. STATISTICS of the project description
Iteration 1 - actor='Citizen' - evidence=Section C. CITIZEN UPDATES of the project description
Iteration 2 - actor='Citizens' - evidence=Section C. CITIZEN UPDATES: 'Once logged into Participium, citizens can follow other citizens’ open reports and receive notifications (following the same rules as for their own reports).'
Iteration 2 - actor='Municipal Operators' - evidence=Section C. CITIZEN UPDATES: 'Municipal operators updating reports can send the reporting citizen a message through the platform, to which it can reply.'
Iteration 4 - actor='Administrator' - evidence=Section D. STATISTICS of the project description
Iteration 5 - actor='Citizens' - evidence=Documentation A: "Citizens can submit reports only if they have registered in the system with a username, first name, and last name... the user gets an email with a confirmation link... the registration becomes valid only after confirming through that link."
Iteration 5 - actor='Citizens' - evidence=Documentation A: "After entering all the information and the pictures, the system asks the citizen whether they want the report to be anonymous (the name will not appear in the public list of all reports)."
Iteration 5 - actor='Citizens' - evidence=Documentation C: "Once logged into Participium, citizens can follow other citizens’ open reports and receive notifications (following the same rules as for their own reports)."
Iteration 5 - actor='Municipal Operators' - evidence=Documentation C: "The system must allow this functionality to be accessible by external chatbots as well."
Iteration 5 - actor='Municipal Administrators' - evidence=Documentation B: "Automatic assignment of all reports in a certain category to the external company (bypassing the initial review ...) is possible only if previously configured by the municipal administrator."

## 4. Consistency check: external outputs vs standalone embedded history

The standalone JSON contains a copy of the iteration evaluations. This check makes sure the separately saved iteration files refer to the same run state. A mismatch should be investigated before interpreting the metrics.

In [19]:
consistency_rows = []
for i, external in external_global.items():
    embedded = embedded_iterations.get(i, {}).get("global_evaluations") or {}
    ext_evals = external.get("evaluations") or {}

    embedded_decisions = {bid: ev.get("decision") for bid, ev in embedded.items()}
    external_decisions = {bid: ev.get("decision") for bid, ev in ext_evals.items()}

    consistency_rows.append({
        "iteration": i,
        "external_branch_count": len(ext_evals),
        "embedded_branch_count": len(embedded),
        "same_branch_ids": set(ext_evals) == set(embedded),
        "same_decisions": external_decisions == embedded_decisions,
    })

consistency_df = pd.DataFrame(consistency_rows)
if len(consistency_df):
    display(consistency_df)
    if not consistency_df[["same_branch_ids", "same_decisions"]].all().all():
        print("WARNING: at least one external iteration file does not match the standalone embedded history.")
else:
    print("No external global-evaluation files were discovered; embedded history is being used.")

,iteration,external_branch_count,embedded_branch_count,same_branch_ids,same_decisions
0,1,5,5,True,True
1,2,5,5,True,True
2,3,5,5,True,True
3,4,5,5,True,True
4,5,5,5,True,True

## 5. Paper-aligned Precision, Recall and F1

The evaluator is loaded once and embeddings are cached. This preserves the original semantic metric while avoiding repeated BERT encoding and silent long-running cells.

In [20]:
BERT_MODEL_NAME = "bert-base-uncased"
BERT_BATCH_SIZE = 16

print(f"Loading {BERT_MODEL_NAME} once...")
print("On the first run, Transformers may need to download the model; later runs use the local cache.")

try:
    tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL_NAME)
    model = AutoModel.from_pretrained(BERT_MODEL_NAME)
except Exception as exc:
    raise RuntimeError(
        "BERT could not be loaded. If this is the first run, make sure the environment "
        "can access Hugging Face long enough to download bert-base-uncased once. "
        "After it is cached, the evaluation can run without downloading it again."
    ) from exc

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words("english"))

print("Device:", device)


class PaperAlignedGoalEvaluator:
    def __init__(self, tokenizer, model, device, batch_size=16, preprocess=True):
        self.tokenizer = tokenizer
        self.model = model
        self.device = device
        self.batch_size = batch_size
        self.preprocess = preprocess
        self.embedding_cache = {}

    def preprocess_text(self, text):
        tokens = word_tokenize(text)
        filtered_tokens = [
            token for token in tokens
            if token not in stop_words and token.isalnum()
        ]
        stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]
        lemmatized_tokens = [lemmatizer.lemmatize(token) for token in stemmed_tokens]
        return " ".join(lemmatized_tokens)

    def _encode_missing(self, raw_texts):
        missing = [text for text in raw_texts if text not in self.embedding_cache]
        if not missing:
            return

        prepared = [
            self.preprocess_text(text) if self.preprocess else text
            for text in missing
        ]

        total_batches = (len(missing) + self.batch_size - 1) // self.batch_size
        iterator = range(0, len(missing), self.batch_size)

        for start in tqdm(iterator, total=total_batches, desc="BERT batches"):
            raw_batch = missing[start:start + self.batch_size]
            text_batch = prepared[start:start + self.batch_size]

            encoded_input = self.tokenizer(
                text_batch,
                padding=True,
                truncation=True,
                return_tensors="pt",
            ).to(self.device)

            with torch.inference_mode():
                model_output = self.model(**encoded_input)

            token_embeddings = model_output.last_hidden_state
            attention_mask = encoded_input["attention_mask"]
            input_mask_expanded = (
                attention_mask.unsqueeze(-1)
                .expand(token_embeddings.size())
                .float()
            )

            sum_embeddings = torch.sum(
                token_embeddings * input_mask_expanded, dim=1
            )
            sum_mask = torch.clamp(
                input_mask_expanded.sum(dim=1), min=1e-9
            )
            pooled = (sum_embeddings / sum_mask).detach().cpu()

            for text, embedding in zip(raw_batch, pooled):
                self.embedding_cache[text] = embedding

    def encode_texts(self, texts):
        self._encode_missing(texts)
        return torch.stack([self.embedding_cache[text] for text in texts])

    def compute_similarity(self, generated_goals, reference_goals):
        gen_embeddings = self.encode_texts(generated_goals)
        ref_embeddings = self.encode_texts(reference_goals)

        gen_norm = torch.nn.functional.normalize(gen_embeddings, p=2, dim=1)
        ref_norm = torch.nn.functional.normalize(ref_embeddings, p=2, dim=1)
        return torch.mm(gen_norm, ref_norm.transpose(0, 1)).numpy()

    def calculate_soft_f1(self, preds, refs):
        if not preds or not refs:
            return {
                "precision": 0.0,
                "recall": 0.0,
                "f1_score": 0.0,
            }

        sim_matrix = self.compute_similarity(preds, refs)
        row_ind, col_ind = linear_sum_assignment(-sim_matrix)
        total_similarity = float(sim_matrix[row_ind, col_ind].sum())

        precision = total_similarity / len(preds)
        recall = total_similarity / len(refs)
        f1 = (
            0.0
            if precision + recall == 0
            else 2 * precision * recall / (precision + recall)
        )

        return {
            "precision": precision,
            "recall": recall,
            "f1_score": f1,
        }


evaluator = PaperAlignedGoalEvaluator(
    tokenizer=tokenizer,
    model=model,
    device=device,
    batch_size=BERT_BATCH_SIZE,
    preprocess=True,
)


def paper_metrics(generated: list[str], reference: list[str]) -> dict[str, float]:
    if not generated or not reference:
        return {"precision": 0.0, "recall": 0.0, "f1": 0.0}

    result = evaluator.calculate_soft_f1(generated, reference)
    return {
        "precision": float(result["precision"]),
        "recall": float(result["recall"]),
        "f1": float(result["f1_score"]),
    }




def evaluate_goal_state(hlg, llg):
    return {
        "hlg": paper_metrics(hlg, REFERENCE_HLG),
        "llg": paper_metrics(llg, REFERENCE_LLG),
    }


print("Evaluating every complete state inspected by the feedback loop...")
ITERATION_METRICS = {}
for state in ITERATION_STATES:
    i = state["iteration"]
    print(f"Iteration {i}: HLG={len(state['hlg'])}, LLG={len(state['llg'])}")
    ITERATION_METRICS[i] = evaluate_goal_state(state["hlg"], state["llg"])

print("Evaluating returned/best/latest states (cached texts are reused)...")
RETURNED_METRICS = evaluate_goal_state(RETURNED_HLG, RETURNED_LLG)
BEST_VALIDATED_METRICS = evaluate_goal_state(BEST_VALIDATED_HLG, BEST_VALIDATED_LLG)
LAST_CANDIDATE_METRICS = evaluate_goal_state(LAST_CANDIDATE_HLG, LAST_CANDIDATE_LLG)

print("Metric computation completed.")

Loading bert-base-uncased once...
On the first run, Transformers may need to download the model; later runs use the local cache.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Device: cpu
Evaluating every complete state inspected by the feedback loop...
Iteration 1: HLG=5, LLG=12

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/2 [00:00<?, ?it/s]

Iteration 2: HLG=5, LLG=12

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration 3: HLG=5, LLG=16

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration 4: HLG=5, LLG=14

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration 5: HLG=5, LLG=19

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluating returned/best/latest states (cached texts are reused)...

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

BERT batches:   0%|          | 0/1 [00:00<?, ?it/s]

Metric computation completed.

## 6. Semantic quality trajectory across iterations

This table is the key view for understanding the feedback loop. Each row evaluates the complete HLG or LLG set that entered one iteration and was therefore inspected by that iteration's evaluator.

In [21]:
trajectory_rows = []
for state in ITERATION_STATES:
    i = state["iteration"]
    m = ITERATION_METRICS[i]
    for level, key, goals in (
        ("High-Level Goals", "hlg", state["hlg"]),
        ("Low-Level Goals", "llg", state["llg"]),
    ):
        metric = m[key]
        trajectory_rows.append({
            "iteration": i,
            "level": level,
            "goal_count": len(goals),
            "precision": metric["precision"],
            "recall": metric["recall"],
            "f1": metric["f1"],
        })

trajectory_df = pd.DataFrame(trajectory_rows)
trajectory_df["delta_f1_vs_baseline"] = trajectory_df.groupby("level")["f1"].transform(lambda s: s - s.iloc[0])
trajectory_df["delta_precision_vs_baseline"] = trajectory_df.groupby("level")["precision"].transform(lambda s: s - s.iloc[0])
trajectory_df["delta_recall_vs_baseline"] = trajectory_df.groupby("level")["recall"].transform(lambda s: s - s.iloc[0])

display(trajectory_df.round(4))

# Best observed evaluated iteration per level (diagnostic, not automatically the final cycle result).
best_rows = []
for level, group in trajectory_df.groupby("level", sort=False):
    best = group.loc[group["f1"].idxmax()]
    best_rows.append(best)
best_observed_df = pd.DataFrame(best_rows).reset_index(drop=True)
print("\nBest observed evaluated state by F1 (diagnostic):")
display(best_observed_df.round(4))

,iteration,level,goal_count,precision,recall,f1,delta_f1_vs_baseline,delta_precision_vs_baseline,delta_recall_vs_baseline
0,1,High-Level Goals,5,0.7036,0.3909,0.5025,0.0000,0.0000,0.0000
1,1,Low-Level Goals,12,0.7306,0.4175,0.5313,0.0000,0.0000,0.0000
2,2,High-Level Goals,5,0.7013,0.3896,0.5009,-0.0016,-0.0023,-0.0013
3,2,Low-Level Goals,12,0.7117,0.4067,0.5176,-0.0138,-0.0189,-0.0108
4,3,High-Level Goals,5,0.7010,0.3894,0.5007,-0.0018,-0.0026,-0.0014
5,3,Low-Level Goals,16,0.6915,0.5268,0.5980,0.0667,-0.0391,0.1094
6,4,High-Level Goals,5,0.6944,0.3858,0.4960,-0.0065,-0.0091,-0.0051
7,4,Low-Level Goals,14,0.7023,0.4682,0.5619,0.0305,-0.0282,0.0507
8,5,High-Level Goals,5,0.6895,0.3831,0.4925,-0.0100,-0.0141,-0.0078
9,5,Low-Level Goals,19,0.6639,0.6007,0.6307,0.0994,-0.0666,0.1832

Best observed evaluated state by F1 (diagnostic):

,iteration,level,goal_count,precision,recall,f1,delta_f1_vs_baseline,delta_precision_vs_baseline,delta_recall_vs_baseline
0,1,High-Level Goals,5,0.7036,0.3909,0.5025,0.0000,0.0000,0.0000
1,5,Low-Level Goals,19,0.6639,0.6007,0.6307,0.0994,-0.0666,0.1832

## 7. Goal cardinality, proliferation and decomposition density

The paper-aligned Precision/Recall/F1 already penalise different set sizes through unmatched items. For this thesis, cardinality is also reported explicitly because the feedback loop can improve coverage by generating many additional goals. These indicators make that trade-off visible.

Reported quantities include the generated/reference count ratio, count excess/deficit, LLG-per-HLG decomposition density, and F1 gain per additional goal. The latter is a diagnostic efficiency indicator and is **not** part of the paper's original metric.

In [22]:
def cardinality_row(state_label, hlg, llg, metrics, iteration=None, state_kind="iteration"):
    base_hlg_count = len(BASELINE_HLG)
    base_llg_count = len(BASELINE_LLG)
    base_metrics = ITERATION_METRICS[ITERATION_STATES[0]["iteration"]]

    hlg_delta_count = len(hlg) - base_hlg_count
    llg_delta_count = len(llg) - base_llg_count
    hlg_delta_f1 = metrics["hlg"]["f1"] - base_metrics["hlg"]["f1"]
    llg_delta_f1 = metrics["llg"]["f1"] - base_metrics["llg"]["f1"]

    return {
        "state": state_label,
        "state_kind": state_kind,
        "iteration": iteration,
        "hlg_count": len(hlg),
        "reference_hlg_count": len(REFERENCE_HLG),
        "hlg_count_ratio": len(hlg) / len(REFERENCE_HLG) if REFERENCE_HLG else np.nan,
        "hlg_count_gap": len(hlg) - len(REFERENCE_HLG),
        "delta_hlg_count_vs_baseline": hlg_delta_count,
        "hlg_precision": metrics["hlg"]["precision"],
        "hlg_recall": metrics["hlg"]["recall"],
        "hlg_f1": metrics["hlg"]["f1"],
        "delta_hlg_f1_vs_baseline": hlg_delta_f1,
        "hlg_f1_gain_per_added_goal": (
            hlg_delta_f1 / hlg_delta_count if hlg_delta_count > 0 else np.nan
        ),
        "llg_count": len(llg),
        "reference_llg_count": len(REFERENCE_LLG),
        "llg_count_ratio": len(llg) / len(REFERENCE_LLG) if REFERENCE_LLG else np.nan,
        "llg_count_gap": len(llg) - len(REFERENCE_LLG),
        "delta_llg_count_vs_baseline": llg_delta_count,
        "llg_precision": metrics["llg"]["precision"],
        "llg_recall": metrics["llg"]["recall"],
        "llg_f1": metrics["llg"]["f1"],
        "delta_llg_f1_vs_baseline": llg_delta_f1,
        "llg_f1_gain_per_added_goal": (
            llg_delta_f1 / llg_delta_count if llg_delta_count > 0 else np.nan
        ),
        "llg_per_hlg": len(llg) / len(hlg) if hlg else np.nan,
        "reference_llg_per_hlg": len(REFERENCE_LLG) / len(REFERENCE_HLG) if REFERENCE_HLG else np.nan,
    }


cardinality_rows = []
for state in ITERATION_STATES:
    i = state["iteration"]
    cardinality_rows.append(
        cardinality_row(
            state_label=f"Iteration {i} evaluated state",
            hlg=state["hlg"],
            llg=state["llg"],
            metrics=ITERATION_METRICS[i],
            iteration=i,
            state_kind="iteration",
        )
    )

for state_label, hlg, llg, metrics, kind in (
    ("Returned state", RETURNED_HLG, RETURNED_LLG, RETURNED_METRICS, "returned"),
    ("Best validated state", BEST_VALIDATED_HLG, BEST_VALIDATED_LLG, BEST_VALIDATED_METRICS, "best_validated"),
    ("Latest candidate (diagnostic)", LAST_CANDIDATE_HLG, LAST_CANDIDATE_LLG, LAST_CANDIDATE_METRICS, "latest_candidate"),
):
    cardinality_rows.append(
        cardinality_row(
            state_label=state_label,
            hlg=hlg,
            llg=llg,
            metrics=metrics,
            iteration=None,
            state_kind=kind,
        )
    )

cardinality_df = pd.DataFrame(cardinality_rows)
display(cardinality_df.round(4))

print("Interpretation of count ratio: 1.0 = same number of goals as ground truth; >1 = over-generation; <1 = under-generation.")

,state,state_kind,iteration,hlg_count,reference_hlg_count,hlg_count_ratio,hlg_count_gap,delta_hlg_count_vs_baseline,hlg_precision,hlg_recall,...,llg_count_ratio,llg_count_gap,delta_llg_count_vs_baseline,llg_precision,llg_recall,llg_f1,delta_llg_f1_vs_baseline,llg_f1_gain_per_added_goal,llg_per_hlg,reference_llg_per_hlg
0,Iteration 1 evaluated state,iteration,1.0,5,9,0.5556,-4,0,0.7036,0.3909,...,0.5714,-9,0,0.7306,0.4175,0.5313,0.0000,NaN,2.4000,2.3333
1,Iteration 2 evaluated state,iteration,2.0,5,9,0.5556,-4,0,0.7013,0.3896,...,0.5714,-9,0,0.7117,0.4067,0.5176,-0.0138,NaN,2.4000,2.3333
2,Iteration 3 evaluated state,iteration,3.0,5,9,0.5556,-4,0,0.7010,0.3894,...,0.7619,-5,4,0.6915,0.5268,0.5980,0.0667,0.0167,3.2000,2.3333
3,Iteration 4 evaluated state,iteration,4.0,5,9,0.5556,-4,0,0.6944,0.3858,...,0.6667,-7,2,0.7023,0.4682,0.5619,0.0305,0.0153,2.8000,2.3333
4,Iteration 5 evaluated state,iteration,5.0,5,9,0.5556,-4,0,0.6895,0.3831,...,0.9048,-2,7,0.6639,0.6007,0.6307,0.0994,0.0142,3.8000,2.3333
5,Returned state,returned,NaN,9,9,1.0000,0,4,0.6278,0.6278,...,1.3333,7,16,0.4854,0.6472,0.5548,0.0234,0.0015,3.1111,2.3333
6,Best validated state,best_validated,NaN,0,9,0.0000,-9,-5,0.0000,0.0000,...,0.0000,-21,-12,0.0000,0.0000,0.0000,-0.5313,NaN,NaN,2.3333
7,Latest candidate (diagnostic),latest_candidate,NaN,9,9,1.0000,0,4,0.6278,0.6278,...,1.3333,7,16,0.4854,0.6472,0.5548,0.0234,0.0015,3.1111,2.3333

Interpretation of count ratio: 1.0 = same number of goals as ground truth; >1 = over-generation; <1 = under-generation.

## 8. Detailed Hungarian matching, unmatched goals and weak semantic matches

This section exposes the assignments that are otherwise collapsed into Precision, Recall and F1. It uses the same BERT cosine-similarity matrix and the same maximum-weight bipartite matching already used by the paper-aligned evaluator.

`UNMATCHED_GENERATED` and `UNMATCHED_REFERENCE` are direct consequences of unequal set cardinalities. `WEAK_MATCH` is an additional thesis diagnostic controlled by `WEAK_MATCH_THRESHOLD`; it does not alter the paper-aligned metrics.

In [23]:
WEAK_MATCH_THRESHOLD = 0.60  # diagnostic only; does not affect Precision/Recall/F1


def matching_rows(generated, reference, level, state_label, iteration=None, state_kind="iteration"):
    rows = []
    matched_generated = set()
    matched_reference = set()

    if generated and reference:
        sim_matrix = evaluator.compute_similarity(generated, reference)
        row_ind, col_ind = linear_sum_assignment(-sim_matrix)

        for gi, ri in zip(row_ind.tolist(), col_ind.tolist()):
            similarity = float(sim_matrix[gi, ri])
            matched_generated.add(gi)
            matched_reference.add(ri)
            rows.append({
                "state": state_label,
                "state_kind": state_kind,
                "iteration": iteration,
                "level": level,
                "generated_index": gi,
                "generated_goal": generated[gi],
                "reference_index": ri,
                "reference_goal": reference[ri],
                "similarity": similarity,
                "match_status": "WEAK_MATCH" if similarity < WEAK_MATCH_THRESHOLD else "MATCHED",
                "weak_match": similarity < WEAK_MATCH_THRESHOLD,
            })

    for gi, goal in enumerate(generated):
        if gi not in matched_generated:
            rows.append({
                "state": state_label,
                "state_kind": state_kind,
                "iteration": iteration,
                "level": level,
                "generated_index": gi,
                "generated_goal": goal,
                "reference_index": np.nan,
                "reference_goal": None,
                "similarity": np.nan,
                "match_status": "UNMATCHED_GENERATED",
                "weak_match": False,
            })

    for ri, goal in enumerate(reference):
        if ri not in matched_reference:
            rows.append({
                "state": state_label,
                "state_kind": state_kind,
                "iteration": iteration,
                "level": level,
                "generated_index": np.nan,
                "generated_goal": None,
                "reference_index": ri,
                "reference_goal": goal,
                "similarity": np.nan,
                "match_status": "UNMATCHED_REFERENCE",
                "weak_match": False,
            })

    return rows


matching_records = []
for state in ITERATION_STATES:
    i = state["iteration"]
    for level, generated, reference in (
        ("High-Level Goals", state["hlg"], REFERENCE_HLG),
        ("Low-Level Goals", state["llg"], REFERENCE_LLG),
    ):
        matching_records.extend(
            matching_rows(
                generated,
                reference,
                level=level,
                state_label=f"Iteration {i} evaluated state",
                iteration=i,
                state_kind="iteration",
            )
        )

for state_label, hlg, llg, state_kind in (
    ("Returned state", RETURNED_HLG, RETURNED_LLG, "returned"),
    ("Best validated state", BEST_VALIDATED_HLG, BEST_VALIDATED_LLG, "best_validated"),
    ("Latest candidate (diagnostic)", LAST_CANDIDATE_HLG, LAST_CANDIDATE_LLG, "latest_candidate"),
):
    matching_records.extend(matching_rows(hlg, REFERENCE_HLG, "High-Level Goals", state_label, state_kind=state_kind))
    matching_records.extend(matching_rows(llg, REFERENCE_LLG, "Low-Level Goals", state_label, state_kind=state_kind))

matching_details_df = pd.DataFrame(matching_records)

matching_summary_rows = []
for (state, state_kind, iteration, level), group in matching_details_df.groupby(
    ["state", "state_kind", "iteration", "level"], dropna=False, sort=False
):
    matched = group[group["match_status"].isin(["MATCHED", "WEAK_MATCH"])]
    matching_summary_rows.append({
        "state": state,
        "state_kind": state_kind,
        "iteration": iteration,
        "level": level,
        "matched_pairs": len(matched),
        "mean_matched_similarity": matched["similarity"].mean() if len(matched) else np.nan,
        "min_matched_similarity": matched["similarity"].min() if len(matched) else np.nan,
        "max_matched_similarity": matched["similarity"].max() if len(matched) else np.nan,
        "weak_matches": int((group["match_status"] == "WEAK_MATCH").sum()),
        "unmatched_generated": int((group["match_status"] == "UNMATCHED_GENERATED").sum()),
        "unmatched_reference": int((group["match_status"] == "UNMATCHED_REFERENCE").sum()),
    })

matching_summary_df = pd.DataFrame(matching_summary_rows)
matching_issues_df = matching_details_df[
    matching_details_df["match_status"].isin(["WEAK_MATCH", "UNMATCHED_GENERATED", "UNMATCHED_REFERENCE"])
].copy()

print("Matching summary:")
display(matching_summary_df.round(4))
print("\nPotential qualitative issues (diagnostic):")
display(matching_issues_df.sort_values(["state_kind", "iteration", "level", "match_status"]).reset_index(drop=True))

Matching summary:

,state,state_kind,iteration,level,matched_pairs,mean_matched_similarity,min_matched_similarity,max_matched_similarity,weak_matches,unmatched_generated,unmatched_reference
0,Iteration 1 evaluated state,iteration,1.0,High-Level Goals,5,0.7036,0.6066,0.7796,0,0,4
1,Iteration 1 evaluated state,iteration,1.0,Low-Level Goals,12,0.7306,0.6810,0.8166,0,0,9
2,Iteration 2 evaluated state,iteration,2.0,High-Level Goals,5,0.7013,0.6346,0.7825,0,0,4
3,Iteration 2 evaluated state,iteration,2.0,Low-Level Goals,12,0.7117,0.6442,0.7692,0,0,9
4,Iteration 3 evaluated state,iteration,3.0,High-Level Goals,5,0.7010,0.6346,0.7825,0,0,4
5,Iteration 3 evaluated state,iteration,3.0,Low-Level Goals,16,0.6915,0.5501,0.8358,2,0,5
6,Iteration 4 evaluated state,iteration,4.0,High-Level Goals,5,0.6944,0.6346,0.7796,0,0,4
7,Iteration 4 evaluated state,iteration,4.0,Low-Level Goals,14,0.7023,0.5893,0.7935,1,0,7
8,Iteration 5 evaluated state,iteration,5.0,High-Level Goals,5,0.6895,0.6346,0.7604,0,0,4
9,Iteration 5 evaluated state,iteration,5.0,Low-Level Goals,19,0.6639,0.4328,0.7935,5,0,2
10,Returned state,returned,NaN,High-Level Goals,9,0.6278,0.4727,0.7604,3,0,0
11,Returned state,returned,NaN,Low-Level Goals,21,0.6472,0.2684,0.8044,7,7,0
12,Best validated state,best_validated,NaN,High-Level Goals,0,NaN,NaN,NaN,0,0,9
13,Best validated state,best_validated,NaN,Low-Level Goals,0,NaN,NaN,NaN,0,0,21
14,Latest candidate (diagnostic),latest_candidate,NaN,High-Level Goals,9,0.6278,0.4727,0.7604,3,0,0
15,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,21,0.6472,0.2684,0.8044,7,7,0

Potential qualitative issues (diagnostic):

,state,state_kind,iteration,level,generated_index,generated_goal,reference_index,reference_goal,similarity,match_status,weak_match
0,Best validated state,best_validated,NaN,High-Level Goals,NaN,NaN,0.0,View Public Statistics,NaN,UNMATCHED_REFERENCE,False
1,Best validated state,best_validated,NaN,High-Level Goals,NaN,NaN,1.0,Register Account,NaN,UNMATCHED_REFERENCE,False
2,Best validated state,best_validated,NaN,High-Level Goals,NaN,NaN,2.0,Submit a report,NaN,UNMATCHED_REFERENCE,False
3,Best validated state,best_validated,NaN,High-Level Goals,NaN,NaN,3.0,Follow reports,NaN,UNMATCHED_REFERENCE,False
4,Best validated state,best_validated,NaN,High-Level Goals,NaN,NaN,4.0,Exchange messages,NaN,UNMATCHED_REFERENCE,False
...,...,...,...,...,...,...,...,...,...,...,...
119,Returned state,returned,NaN,Low-Level Goals,11.0,Allows municipal operators to view all reports...,2.0,Fill-in a report,0.441791,WEAK_MATCH,True
120,Returned state,returned,NaN,Low-Level Goals,13.0,Allows municipal operators to delegate the han...,12.0,Deactivate auto-assignment for a category,0.554477,WEAK_MATCH,True
121,Returned state,returned,NaN,Low-Level Goals,14.0,Enables municipal operators to change the stat...,20.0,Log-in,0.268431,WEAK_MATCH,True
122,Returned state,returned,NaN,Low-Level Goals,16.0,Enables municipal operators to create a summar...,4.0,Select anonimity for a report,0.590953,WEAK_MATCH,True
123,Returned state,returned,NaN,Low-Level Goals,26.0,Allows municipal administrators to assign acce...,11.0,Activate auto-assignment for a category,0.557617,WEAK_MATCH,True

## 9. Ground-truth goal recovery and degradation across feedback iterations

For every reference goal, this table follows the similarity of its Hungarian-assigned generated goal across iterations. An unmatched reference goal receives similarity `0.0` for that iteration. This makes it possible to identify which ground-truth intentions are recovered, improved, degraded, or lost as the feedback loop evolves.

In [24]:
MATERIAL_SIMILARITY_DELTA = 0.05  # descriptive threshold only

iteration_matching_df = matching_details_df[matching_details_df["state_kind"] == "iteration"].copy()
iteration_ids = sorted(state["iteration"] for state in ITERATION_STATES)
baseline_iteration = iteration_ids[0]
latest_evaluated_iteration = iteration_ids[-1]

reference_trace_rows = []
for level, references in (
    ("High-Level Goals", REFERENCE_HLG),
    ("Low-Level Goals", REFERENCE_LLG),
):
    for ri, reference_goal in enumerate(references):
        similarities = {}
        generated_matches = {}
        for i in iteration_ids:
            subset = iteration_matching_df[
                (iteration_matching_df["iteration"] == i)
                & (iteration_matching_df["level"] == level)
                & (iteration_matching_df["reference_index"] == ri)
            ]
            if len(subset):
                row = subset.iloc[0]
                similarities[i] = 0.0 if row["match_status"] == "UNMATCHED_REFERENCE" else float(row["similarity"])
                generated_matches[i] = row["generated_goal"]
            else:
                similarities[i] = 0.0
                generated_matches[i] = None

        baseline_sim = similarities[baseline_iteration]
        latest_sim = similarities[latest_evaluated_iteration]
        best_iteration = max(similarities, key=similarities.get)
        best_sim = similarities[best_iteration]
        delta_latest = latest_sim - baseline_sim

        if delta_latest >= MATERIAL_SIMILARITY_DELTA:
            change = "IMPROVED"
        elif delta_latest <= -MATERIAL_SIMILARITY_DELTA:
            change = "DEGRADED"
        else:
            change = "STABLE"

        row = {
            "level": level,
            "reference_index": ri,
            "reference_goal": reference_goal,
            "baseline_iteration": baseline_iteration,
            "baseline_similarity": baseline_sim,
            "latest_evaluated_iteration": latest_evaluated_iteration,
            "latest_similarity": latest_sim,
            "delta_latest_vs_baseline": delta_latest,
            "best_iteration": best_iteration,
            "best_similarity": best_sim,
            "delta_best_vs_baseline": best_sim - baseline_sim,
            "latest_change_class": change,
            "baseline_generated_match": generated_matches[baseline_iteration],
            "latest_generated_match": generated_matches[latest_evaluated_iteration],
            "best_generated_match": generated_matches[best_iteration],
        }
        for i in iteration_ids:
            row[f"similarity_iteration_{i}"] = similarities[i]
        reference_trace_rows.append(row)

reference_goal_trajectory_df = pd.DataFrame(reference_trace_rows)

print("Ground-truth goals with the largest improvements:")
display(
    reference_goal_trajectory_df.sort_values("delta_latest_vs_baseline", ascending=False)
    .head(15)
    .reset_index(drop=True)
    .round(4)
)

print("\nGround-truth goals with the largest degradations:")
display(
    reference_goal_trajectory_df.sort_values("delta_latest_vs_baseline", ascending=True)
    .head(15)
    .reset_index(drop=True)
    .round(4)
)

recovery_summary_df = (
    reference_goal_trajectory_df.groupby(["level", "latest_change_class"], dropna=False)
    .size()
    .unstack(fill_value=0)
    .reset_index()
)
print("\nRecovery/degradation summary:")
display(recovery_summary_df)

Ground-truth goals with the largest improvements:

,level,reference_index,reference_goal,baseline_iteration,baseline_similarity,latest_evaluated_iteration,latest_similarity,delta_latest_vs_baseline,best_iteration,best_similarity,delta_best_vs_baseline,latest_change_class,baseline_generated_match,latest_generated_match,best_generated_match,similarity_iteration_1,similarity_iteration_2,similarity_iteration_3,similarity_iteration_4,similarity_iteration_5
0,Low-Level Goals,19,View the details of a report,1,0.0000,5,0.6826,0.6826,3,0.6826,0.6826,IMPROVED,NaN,Allow non-registered users to access and view ...,Allow non-registered users to access and view ...,0.0000,0.0000,0.6826,0.6826,0.6826
1,Low-Level Goals,13,Approve a report,1,0.0000,5,0.6534,0.6534,5,0.6534,0.6534,IMPROVED,NaN,Enables municipal operators to quickly locate ...,Enables municipal operators to quickly locate ...,0.0000,0.6442,0.6130,0.5893,0.6534
2,High-Level Goals,1,Register Account,1,0.0000,5,0.6393,0.6393,2,0.6393,0.6393,IMPROVED,NaN,The stakeholder aims to access relevant inform...,The stakeholder aims to access relevant inform...,0.0000,0.6393,0.6393,0.6393,0.6393
3,Low-Level Goals,4,Select anonimity for a report,1,0.0000,5,0.5857,0.5857,5,0.5857,0.5857,IMPROVED,NaN,Allows municipal operators to be alerted when ...,Allows municipal operators to be alerted when ...,0.0000,0.0000,0.5501,0.0000,0.5857
4,Low-Level Goals,0,Activate account,1,0.0000,5,0.5758,0.5758,3,0.5902,0.5902,IMPROVED,NaN,Enable non-registered users to view statistics...,Enable municipal administrators to view statis...,0.0000,0.0000,0.5902,0.0000,0.5758
5,Low-Level Goals,12,Deactivate auto-assignment for a category,1,0.0000,5,0.5566,0.5566,5,0.5566,0.5566,IMPROVED,NaN,Enables municipal operators to change the stat...,Enables municipal operators to change the stat...,0.0000,0.0000,0.0000,0.0000,0.5566
6,Low-Level Goals,11,Activate auto-assignment for a category,1,0.0000,5,0.5427,0.5427,5,0.5427,0.5427,IMPROVED,NaN,Allows municipal operators to delegate the han...,Allows municipal operators to delegate the han...,0.0000,0.0000,0.0000,0.0000,0.5427
7,Low-Level Goals,6,Send a message,1,0.0000,5,0.4328,0.4328,5,0.4328,0.4328,IMPROVED,NaN,This API call enables external maintenance per...,This API call enables external maintenance per...,0.0000,0.0000,0.0000,0.0000,0.4328
8,Low-Level Goals,3,Associate a report with a specific location on...,1,0.6980,5,0.7190,0.0210,4,0.7190,0.0210,STABLE,Municipal administrators can monitor the statu...,Citizens can interact with a map interface to ...,Citizens can interact with a map interface to ...,0.6980,0.0000,0.6750,0.7190,0.7190
9,High-Level Goals,7,Configure report auto-assignment,1,0.7475,5,0.7604,0.0129,2,0.7825,0.0349,STABLE,Municipal administrators require administrativ...,The stakeholder aims to have a comprehensive t...,The stakeholder aims to ensure efficient manag...,0.7475,0.7825,0.7825,0.7253,0.7604
10,Low-Level Goals,1,Submit account registration,1,0.7156,5,0.7221,0.0065,5,0.7221,0.0065,STABLE,Municipal operators can access a dashboard tha...,Allows municipal operators to view all reports...,Allows municipal operators to view all reports...,0.7156,0.7156,0.6922,0.7156,0.7221
11,Low-Level Goals,18,Add a report to the set of followed reports,1,0.7153,5,0.7192,0.0039,4,0.7192,0.0039,STABLE,External maintenance personnel can communicate...,This API call allows external maintenance pers...,This API call allows external maintenance pers...,0.7153,0.6771,0.7168,0.7192,0.7192
12,High-Level Goals,0,View Public Statistics,1,0.0000,5,0.0000,0.0000,1,0.0000,0.0000,STABLE,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000
13,High-Level Goals,6,View private statistics,1,0.0000,5,0.0000,0.0000,1,0.0000,0.0000,STABLE,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000
14,Low-Level Goals,20,Log-in,1,0.0000,5,0.0000,0.0000,1,0.0000,0.0000,STABLE,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000

Ground-truth goals with the largest degradations:

,level,reference_index,reference_goal,baseline_iteration,baseline_similarity,latest_evaluated_iteration,latest_similarity,delta_latest_vs_baseline,best_iteration,best_similarity,delta_best_vs_baseline,latest_change_class,baseline_generated_match,latest_generated_match,best_generated_match,similarity_iteration_1,similarity_iteration_2,similarity_iteration_3,similarity_iteration_4,similarity_iteration_5
0,High-Level Goals,4,Exchange messages,1,0.6066,5,0.0000,-0.6066,1,0.6066,0.0000,DEGRADED,External maintenance personnel should have acc...,NaN,External maintenance personnel should have acc...,0.6066,0.0000,0.0000,0.0000,0.0000
1,Low-Level Goals,16,Add a comment related to a report,1,0.7971,5,0.7169,-0.0803,1,0.7971,0.0000,DEGRADED,Non-registered users can access a public inter...,This API call allows municipal administrators ...,Non-registered users can access a public inter...,0.7971,0.7560,0.7560,0.7591,0.7169
2,High-Level Goals,5,Manage report lifecycle,1,0.7796,5,0.7198,-0.0598,1,0.7796,0.0000,DEGRADED,"Municipal operators need tools to review, appr...",The stakeholder aims to streamline the managem...,"Municipal operators need tools to review, appr...",0.7796,0.7796,0.7796,0.7796,0.7198
3,High-Level Goals,8,Manage account information,1,0.7495,5,0.6935,-0.0560,1,0.7495,0.0000,DEGRADED,Non-registered users should be able to view pu...,This goal focuses on providing external mainte...,Non-registered users should be able to view pu...,0.7495,0.6705,0.6691,0.6935,0.6935
4,Low-Level Goals,15,Update the report's status,1,0.7264,5,0.6829,-0.0435,1,0.7264,0.0000,STABLE,Citizens can interact with a map interface to ...,Enables municipal operators to create a summar...,Citizens can interact with a map interface to ...,0.7264,0.7264,0.7264,0.6265,0.6829
5,Low-Level Goals,8,Deactivate email notifications,1,0.7205,5,0.6859,-0.0346,1,0.7205,0.0000,STABLE,Municipal administrators can access configurat...,This API call enables external maintenance per...,Municipal administrators can access configurat...,0.7205,0.6562,0.6925,0.6859,0.6859
6,Low-Level Goals,17,Assign a report to an external company,1,0.8166,5,0.7935,-0.0231,3,0.8358,0.0192,STABLE,External maintenance personnel can view the re...,This API call allows external maintenance pers...,Allow external maintenance personnel to commun...,0.8166,0.7607,0.8358,0.7935,0.7935
7,Low-Level Goals,10,Delete a profile photo,1,0.7385,5,0.7222,-0.0163,1,0.7385,0.0000,STABLE,Municipal operators can delegate specific repo...,Enables municipal operators to mark a report a...,Municipal operators can delegate specific repo...,0.7385,0.7385,0.7385,0.7385,0.7222
8,Low-Level Goals,14,Reject a report specifying the rejection reason,1,0.7692,5,0.7542,-0.0151,1,0.7692,0.0000,STABLE,Municipal operators can take action on reports...,This API call enables municipal administrators...,Municipal operators can take action on reports...,0.7692,0.7692,0.7451,0.7542,0.7542
9,Low-Level Goals,9,Upload a profile photo,1,0.6810,5,0.6806,-0.0005,2,0.7074,0.0263,STABLE,Non-registered users can apply filters to view...,Allows municipal operators to document additio...,Allow non-registered users to access and view ...,0.6810,0.7074,0.6607,0.6607,0.6806
10,Low-Level Goals,5,Submit a report,1,0.6829,5,0.6829,0.0000,1,0.6829,0.0000,STABLE,Citizens can submit the completed report form ...,Citizens can submit the completed report form ...,Citizens can submit the completed report form ...,0.6829,0.6829,0.6829,0.6829,0.6829
11,High-Level Goals,0,View Public Statistics,1,0.0000,5,0.0000,0.0000,1,0.0000,0.0000,STABLE,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000
12,High-Level Goals,6,View private statistics,1,0.0000,5,0.0000,0.0000,1,0.0000,0.0000,STABLE,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000
13,High-Level Goals,3,Follow reports,1,0.0000,5,0.0000,0.0000,1,0.0000,0.0000,STABLE,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000
14,Low-Level Goals,2,Fill-in a report,1,0.0000,5,0.0000,0.0000,1,0.0000,0.0000,STABLE,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000

Recovery/degradation summary:

latest_change_class             level  DEGRADED  IMPROVED  STABLE
0                    High-Level Goals         3         1       5
1                     Low-Level Goals         1         7      13

## 10. Semantic redundancy and duplicate proliferation (diagnostic)

The paper does not define a duplicate-rate metric, but this extension is useful for the thesis because a feedback loop can inflate recall by generating semantically overlapping HLGs or LLGs. Pairwise BERT cosine similarity is therefore used to flag highly similar goals within the same generated set.

`SEMANTIC_DUPLICATE_THRESHOLD` is configurable and **does not affect** the paper-aligned Precision/Recall/F1 results.

In [25]:
SEMANTIC_DUPLICATE_THRESHOLD = 0.85


def duplicate_pairs(goals, level, state_label, iteration=None, state_kind="iteration"):
    if len(goals) < 2:
        return []

    sim_matrix = evaluator.compute_similarity(goals, goals)
    rows = []
    for i in range(len(goals)):
        for j in range(i + 1, len(goals)):
            similarity = float(sim_matrix[i, j])
            if similarity >= SEMANTIC_DUPLICATE_THRESHOLD:
                rows.append({
                    "state": state_label,
                    "state_kind": state_kind,
                    "iteration": iteration,
                    "level": level,
                    "goal_index_a": i,
                    "goal_a": goals[i],
                    "goal_index_b": j,
                    "goal_b": goals[j],
                    "similarity": similarity,
                })
    return rows


duplicate_pair_records = []
duplicate_summary_rows = []

for state in ITERATION_STATES:
    i = state["iteration"]
    for level, goals in (("High-Level Goals", state["hlg"]), ("Low-Level Goals", state["llg"])):
        pairs = duplicate_pairs(
            goals,
            level=level,
            state_label=f"Iteration {i} evaluated state",
            iteration=i,
            state_kind="iteration",
        )
        duplicate_pair_records.extend(pairs)
        duplicate_goal_indices = set()
        for p in pairs:
            duplicate_goal_indices.add(p["goal_index_a"])
            duplicate_goal_indices.add(p["goal_index_b"])
        duplicate_summary_rows.append({
            "state": f"Iteration {i} evaluated state",
            "state_kind": "iteration",
            "iteration": i,
            "level": level,
            "goal_count": len(goals),
            "duplicate_pair_count": len(pairs),
            "goals_in_duplicate_pairs": len(duplicate_goal_indices),
            "duplicate_goal_rate": len(duplicate_goal_indices) / len(goals) if goals else 0.0,
            "max_duplicate_similarity": max((p["similarity"] for p in pairs), default=np.nan),
        })

for state_label, hlg, llg, state_kind in (
    ("Returned state", RETURNED_HLG, RETURNED_LLG, "returned"),
    ("Best validated state", BEST_VALIDATED_HLG, BEST_VALIDATED_LLG, "best_validated"),
    ("Latest candidate (diagnostic)", LAST_CANDIDATE_HLG, LAST_CANDIDATE_LLG, "latest_candidate"),
):
    for level, goals in (("High-Level Goals", hlg), ("Low-Level Goals", llg)):
        pairs = duplicate_pairs(goals, level=level, state_label=state_label, state_kind=state_kind)
        duplicate_pair_records.extend(pairs)
        duplicate_goal_indices = set()
        for p in pairs:
            duplicate_goal_indices.update([p["goal_index_a"], p["goal_index_b"]])
        duplicate_summary_rows.append({
            "state": state_label,
            "state_kind": state_kind,
            "iteration": np.nan,
            "level": level,
            "goal_count": len(goals),
            "duplicate_pair_count": len(pairs),
            "goals_in_duplicate_pairs": len(duplicate_goal_indices),
            "duplicate_goal_rate": len(duplicate_goal_indices) / len(goals) if goals else 0.0,
            "max_duplicate_similarity": max((p["similarity"] for p in pairs), default=np.nan),
        })

duplicate_pairs_df = pd.DataFrame(duplicate_pair_records)
duplicate_summary_df = pd.DataFrame(duplicate_summary_rows)

display(duplicate_summary_df.round(4))
if len(duplicate_pairs_df):
    print("\nHighest-similarity potential duplicate pairs:")
    display(duplicate_pairs_df.sort_values("similarity", ascending=False).head(30).reset_index(drop=True).round(4))
else:
    print("No semantic duplicate pair exceeded the configured threshold.")

,state,state_kind,iteration,level,goal_count,duplicate_pair_count,goals_in_duplicate_pairs,duplicate_goal_rate,max_duplicate_similarity
0,Iteration 1 evaluated state,iteration,1.0,High-Level Goals,5,3,3,0.6000,0.8576
1,Iteration 1 evaluated state,iteration,1.0,Low-Level Goals,12,20,11,0.9167,0.9007
2,Iteration 2 evaluated state,iteration,2.0,High-Level Goals,5,3,3,0.6000,0.9001
3,Iteration 2 evaluated state,iteration,2.0,Low-Level Goals,12,18,11,0.9167,0.9007
4,Iteration 3 evaluated state,iteration,3.0,High-Level Goals,5,1,2,0.4000,0.9001
5,Iteration 3 evaluated state,iteration,3.0,Low-Level Goals,16,28,16,1.0000,0.9155
6,Iteration 4 evaluated state,iteration,4.0,High-Level Goals,5,3,3,0.6000,0.8844
7,Iteration 4 evaluated state,iteration,4.0,Low-Level Goals,14,24,12,0.8571,0.9086
8,Iteration 5 evaluated state,iteration,5.0,High-Level Goals,5,6,4,0.8000,0.8844
9,Iteration 5 evaluated state,iteration,5.0,Low-Level Goals,19,39,17,0.8947,0.9181
10,Returned state,returned,NaN,High-Level Goals,9,13,7,0.7778,0.9138
11,Returned state,returned,NaN,Low-Level Goals,28,53,24,0.8571,0.9181
12,Best validated state,best_validated,NaN,High-Level Goals,0,0,0,0.0000,NaN
13,Best validated state,best_validated,NaN,Low-Level Goals,0,0,0,0.0000,NaN
14,Latest candidate (diagnostic),latest_candidate,NaN,High-Level Goals,9,13,7,0.7778,0.9138
15,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,28,53,24,0.8571,0.9181

Highest-similarity potential duplicate pairs:

,state,state_kind,iteration,level,goal_index_a,goal_a,goal_index_b,goal_b,similarity
0,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,12,Enables municipal operators to mark a report a...,18,Enables municipal operators to quickly locate ...,0.9181
1,Returned state,returned,NaN,Low-Level Goals,12,Enables municipal operators to mark a report a...,18,Enables municipal operators to quickly locate ...,0.9181
2,Iteration 5 evaluated state,iteration,5.0,Low-Level Goals,12,Enables municipal operators to mark a report a...,18,Enables municipal operators to quickly locate ...,0.9181
3,Iteration 3 evaluated state,iteration,3.0,Low-Level Goals,14,Allow external maintenance personnel to commun...,15,Enable external maintenance personnel to get a...,0.9155
4,Returned state,returned,NaN,Low-Level Goals,20,Triggers the system to send a confirmation ema...,21,Allows citizens to confirm their email address...,0.9150
5,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,20,Triggers the system to send a confirmation ema...,21,Allows citizens to confirm their email address...,0.9150
6,Iteration 3 evaluated state,iteration,3.0,Low-Level Goals,11,Enable external maintenance personnel to fetch...,15,Enable external maintenance personnel to get a...,0.9146
7,Latest candidate (diagnostic),latest_candidate,NaN,High-Level Goals,4,The stakeholder aims to access relevant inform...,5,This goal ensures that citizens can create a v...,0.9138
8,Returned state,returned,NaN,High-Level Goals,4,The stakeholder aims to access relevant inform...,5,This goal ensures that citizens can create a v...,0.9138
9,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,26,Allows municipal administrators to assign acce...,27,Enables municipal administrators to remove acc...,0.9137
10,Returned state,returned,NaN,Low-Level Goals,26,Allows municipal administrators to assign acce...,27,Enables municipal administrators to remove acc...,0.9137
11,Iteration 3 evaluated state,iteration,3.0,Low-Level Goals,12,Allow external maintenance personnel to modify...,14,Allow external maintenance personnel to commun...,0.9120
12,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,10,This API call allows municipal administrators ...,15,Allows municipal operators to document additio...,0.9090
13,Iteration 5 evaluated state,iteration,5.0,Low-Level Goals,10,This API call allows municipal administrators ...,15,Allows municipal operators to document additio...,0.9090
14,Returned state,returned,NaN,Low-Level Goals,10,This API call allows municipal administrators ...,15,Allows municipal operators to document additio...,0.9090
15,Returned state,returned,NaN,Low-Level Goals,9,This API call enables municipal administrators...,10,This API call allows municipal administrators ...,0.9086
16,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,9,This API call enables municipal administrators...,10,This API call allows municipal administrators ...,0.9086
17,Iteration 4 evaluated state,iteration,4.0,Low-Level Goals,12,This API call enables municipal administrators...,13,This API call allows municipal administrators ...,0.9086
18,Iteration 5 evaluated state,iteration,5.0,Low-Level Goals,9,This API call enables municipal administrators...,10,This API call allows municipal administrators ...,0.9086
19,Iteration 4 evaluated state,iteration,4.0,Low-Level Goals,8,This API call enables external maintenance per...,12,This API call enables municipal administrators...,0.9070
20,Returned state,returned,NaN,Low-Level Goals,5,This API call enables external maintenance per...,9,This API call enables municipal administrators...,0.9070
21,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,5,This API call enables external maintenance per...,9,This API call enables municipal administrators...,0.9070
22,Iteration 5 evaluated state,iteration,5.0,Low-Level Goals,5,This API call enables external maintenance per...,9,This API call enables municipal administrators...,0.9070
23,Latest candidate (diagnostic),latest_candidate,NaN,Low-Level Goals,1,Citizens can provide specific information abou...,15,Allows municipal operators to document additio...,0.9066
24,Returned state,returned,NaN,Low-Level Goals,1,Citizens can provide specific information abou...,15,Allows municipal operators to document additio...,0.9066
25,Iteration 5 evaluated state,iteration,5.0,Low-Level Goals,1,Citizens can provide specific information abou...,15,Allows municipal operators to document additio...,0.9066
26,Iteration 4 evaluated state,iteration,4.0,Low-Level Goals,1,Citizens can provide specific information abou...,3,Municipal operators can access a dashboard tha...,0.9007
27,Iteration 1 evaluated state,iteration,1.0,Low-Level Goals,1,Citizens can provide specific information abou...,3,Municipal operators can access a dashboard tha...,0.9007
28,Iteration 3 evaluated state,iteration,3.0,Low-Level Goals,1,Citizens can provide specific information abou...,3,Municipal operators can access a dashboard tha...,0.9007
29,Iteration 2 evaluated state,iteration,2.0,Low-Level Goals,1,Citizens can provide specific information abou...,3,Municipal operators can access a dashboard tha...,0.9007

## 11. Actor-level proliferation and branch-feedback diagnostics

Because this thesis evaluates a feedback loop over a single case study, a useful analogue to the paper's per-dataset breakdown is a per-actor breakdown. The table below combines the number of HLGs/LLGs assigned to each actor with branch decisions, regeneration requests, documentation gaps, and newly added HLGs.

These are structural/diagnostic indicators; actor-specific semantic Precision/Recall/F1 cannot be computed unless the ground truth itself provides actor labels for every reference goal.

In [26]:
def actor_from_hlg(item):
    if not isinstance(item, dict):
        return "UNKNOWN"
    actor = item.get("actor") or {}
    return actor.get("name") or "UNKNOWN"


def actor_from_llg(item):
    if not isinstance(item, dict):
        return "UNKNOWN"
    parent = item.get("high_level_associated") or {}
    actor = parent.get("actor") or {}
    return actor.get("name") or "UNKNOWN"


actor_rows = []
for i, it in sorted(embedded_iterations.items()):
    hlg_items = (it.get("input_high_level_goals") or {}).get("goals", []) or []
    llg_items = (it.get("input_low_level_goals") or {}).get("low_level_goals", []) or []

    hlg_counts = Counter(actor_from_hlg(x) for x in hlg_items)
    llg_counts = Counter(actor_from_llg(x) for x in llg_items)

    newly_added_counts = Counter(
        actor_from_hlg(x) for x in (it.get("newly_added_high_level_goals") or [])
    )

    global_eval = GLOBAL_AUDIT.get(i, {}).get("evaluations") or {}
    eval_by_actor = {}
    for branch_id, ev in global_eval.items():
        original = ev.get("original_high_level_goal") or {}
        actor = actor_from_hlg(original)
        bucket = eval_by_actor.setdefault(actor, Counter())
        bucket["evaluated_branches"] += 1
        bucket[f"decision::{ev.get('decision', 'UNKNOWN')}"] += 1
        bucket["requires_hlg_regeneration"] += int(bool(ev.get("requires_high_level_regeneration")))
        bucket["requires_llg_regeneration"] += int(bool(ev.get("requires_low_level_regeneration")))

    cov = coverage_payload(COVERAGE_AUDIT.get(i))
    missing_doc_counts = Counter()
    if cov:
        for item in cov.get("missing_high_level_goals", []) or []:
            actor = ((item.get("actor") or {}).get("name") or "UNKNOWN")
            missing_doc_counts[actor] += 1

    actors = sorted(set(hlg_counts) | set(llg_counts) | set(newly_added_counts) | set(eval_by_actor) | set(missing_doc_counts))
    for actor in actors:
        bucket = eval_by_actor.get(actor, Counter())
        evaluated = bucket.get("evaluated_branches", 0)
        confirm = bucket.get("decision::CONFIRM_BRANCH", 0)
        actor_rows.append({
            "iteration": i,
            "actor": actor,
            "hlg_count": hlg_counts.get(actor, 0),
            "llg_count": llg_counts.get(actor, 0),
            "llg_per_hlg": llg_counts.get(actor, 0) / hlg_counts.get(actor, 0) if hlg_counts.get(actor, 0) else np.nan,
            "newly_added_hlg": newly_added_counts.get(actor, 0),
            "missing_documentation_hlg": missing_doc_counts.get(actor, 0),
            "evaluated_branches": evaluated,
            "confirm_branch": confirm,
            "matches_other_hlg": bucket.get("decision::MATCHES_OTHER_HIGH_LEVEL_GOAL", 0),
            "other_decisions": sum(
                v for k, v in bucket.items()
                if k.startswith("decision::") and k not in {
                    "decision::CONFIRM_BRANCH",
                    "decision::MATCHES_OTHER_HIGH_LEVEL_GOAL",
                }
            ),
            "requires_hlg_regeneration": bucket.get("requires_hlg_regeneration", 0),
            "requires_llg_regeneration": bucket.get("requires_llg_regeneration", 0),
            "confirm_rate": confirm / evaluated if evaluated else np.nan,
        })

actor_feedback_df = pd.DataFrame(actor_rows)

# Add actor-specific count deltas against iteration 1 where the actor already existed.
baseline_actor_counts = (
    actor_feedback_df[actor_feedback_df["iteration"] == baseline_iteration]
    .set_index("actor")[["hlg_count", "llg_count"]]
    .to_dict("index")
)

actor_feedback_df["delta_hlg_count_vs_iteration1"] = actor_feedback_df.apply(
    lambda r: r["hlg_count"] - baseline_actor_counts.get(r["actor"], {}).get("hlg_count", 0), axis=1
)
actor_feedback_df["delta_llg_count_vs_iteration1"] = actor_feedback_df.apply(
    lambda r: r["llg_count"] - baseline_actor_counts.get(r["actor"], {}).get("llg_count", 0), axis=1
)

display(actor_feedback_df.sort_values(["iteration", "actor"]).reset_index(drop=True).round(4))

,iteration,actor,hlg_count,llg_count,llg_per_hlg,newly_added_hlg,missing_documentation_hlg,evaluated_branches,confirm_branch,matches_other_hlg,other_decisions,requires_hlg_regeneration,requires_llg_regeneration,confirm_rate,delta_hlg_count_vs_iteration1,delta_llg_count_vs_iteration1
0,1,Citizen,0,0,NaN,0,1,0,0,0,0,0,0,NaN,0,0
1,1,Citizens,1,3,3.0,0,0,1,1,0,0,0,0,1.0,0,0
2,1,External Maintenance Personnel,1,2,2.0,0,0,1,0,0,1,1,1,0.0,0,0
3,1,Municipal Administrators,1,2,2.0,0,0,1,0,0,1,1,1,0.0,0,0
4,1,Municipal Operators,1,3,3.0,0,0,1,1,0,0,0,0,1.0,0,0
5,1,Non-registered Users,1,2,2.0,0,0,1,0,0,1,1,1,0.0,0,0
6,1,Public,0,0,NaN,0,1,0,0,0,0,0,0,NaN,0,0
7,2,Citizens,1,3,3.0,0,1,1,1,0,0,0,0,1.0,0,0
8,2,External Maintenance Personnel,1,2,2.0,0,0,1,0,0,1,1,1,0.0,0,0
9,2,Municipal Administrators,1,2,2.0,0,0,1,1,0,0,0,0,1.0,0,0
10,2,Municipal Operators,1,3,3.0,0,1,1,1,0,0,0,0,1.0,0,0
11,2,Non-registered Users,1,2,2.0,0,0,1,1,0,0,0,0,1.0,0,0
12,3,Citizens,1,3,3.0,0,0,1,1,0,0,0,0,1.0,0,0
13,3,External Maintenance Personnel,1,6,6.0,0,0,1,0,0,1,1,1,0.0,0,4
14,3,Municipal Administrators,1,2,2.0,0,0,1,0,0,1,1,1,0.0,0,0
15,3,Municipal Operators,1,3,3.0,0,0,1,1,0,0,0,0,1.0,0,0
16,3,Non-registered Users,1,2,2.0,0,0,1,1,0,0,0,0,1.0,0,0
17,4,Administrator,0,0,NaN,0,1,0,0,0,0,0,0,NaN,0,0
18,4,Citizens,1,3,3.0,0,0,1,1,0,0,0,0,1.0,0,0
19,4,External Maintenance Personnel,1,4,4.0,0,0,1,1,0,0,0,0,1.0,0,2
20,4,Municipal Administrators,1,2,2.0,0,0,1,1,0,0,0,0,1.0,0,0
21,4,Municipal Operators,1,3,3.0,0,0,1,0,0,1,1,1,0.0,0,0
22,4,Non-registered Users,1,2,2.0,0,0,1,1,0,0,0,0,1.0,0,0
23,5,Citizens,1,3,3.0,2,3,1,1,0,0,0,0,1.0,0,0
24,5,External Maintenance Personnel,1,4,4.0,0,0,1,1,0,0,0,0,1.0,0,2
25,5,Municipal Administrators,1,2,2.0,1,1,1,1,0,0,0,0,1.0,0,0
26,5,Municipal Operators,1,8,8.0,1,1,1,1,0,0,0,0,1.0,0,5
27,5,Non-registered Users,1,2,2.0,0,0,1,1,0,0,0,0,1.0,0,0

## 12. Baseline vs returned state vs latest candidate

This table preserves the distinction between the state returned by the orchestrator, the best validated state, and the latest candidate. When the cycle has not converged, the latest candidate is diagnostic evidence only and must not be reported as a successful final result.

In [27]:
baseline_metrics = ITERATION_METRICS[ITERATION_STATES[0]["iteration"]]

comparison_rows = []
for level, key in (("High-Level Goals", "hlg"), ("Low-Level Goals", "llg")):
    base = baseline_metrics[key]
    for state_name, metrics, is_final in (
        ("Returned state", RETURNED_METRICS[key], True),
        ("Best validated state", BEST_VALIDATED_METRICS[key], True),
        ("Latest candidate (diagnostic)", LAST_CANDIDATE_METRICS[key], bool(cycle.get("converged"))),
    ):
        comparison_rows.append({
            "level": level,
            "state": state_name,
            "baseline_precision": base["precision"],
            "state_precision": metrics["precision"],
            "delta_precision": metrics["precision"] - base["precision"],
            "baseline_recall": base["recall"],
            "state_recall": metrics["recall"],
            "delta_recall": metrics["recall"] - base["recall"],
            "baseline_f1": base["f1"],
            "state_f1": metrics["f1"],
            "delta_f1": metrics["f1"] - base["f1"],
            "cycle_converged": bool(cycle.get("converged")),
            "safe_to_report_as_converged_feedback_result": bool(is_final and cycle.get("converged")),
        })

comparison_df = pd.DataFrame(comparison_rows)
display(comparison_df.round(4))

print("\nCycle converged:", bool(cycle.get("converged")))
print("Stop reason:", cycle.get("stop_reason"))
if not cycle.get("converged"):
    print(
        "The latest-candidate and trajectory metrics can be discussed as diagnostic evidence of the loop, "
        "but they must not be labelled as a converged final feedback result."
    )

,level,state,baseline_precision,state_precision,delta_precision,baseline_recall,state_recall,delta_recall,baseline_f1,state_f1,delta_f1,cycle_converged,safe_to_report_as_converged_feedback_result
0,High-Level Goals,Returned state,0.7036,0.6278,-0.0757,0.3909,0.6278,0.2370,0.5025,0.6278,0.1253,False,False
1,High-Level Goals,Best validated state,0.7036,0.0000,-0.7036,0.3909,0.0000,-0.3909,0.5025,0.0000,-0.5025,False,False
2,High-Level Goals,Latest candidate (diagnostic),0.7036,0.6278,-0.0757,0.3909,0.6278,0.2370,0.5025,0.6278,0.1253,False,False
3,Low-Level Goals,Returned state,0.7306,0.4854,-0.2452,0.4175,0.6472,0.2298,0.5313,0.5548,0.0234,False,False
4,Low-Level Goals,Best validated state,0.7306,0.0000,-0.7306,0.4175,0.0000,-0.4175,0.5313,0.0000,-0.5313,False,False
5,Low-Level Goals,Latest candidate (diagnostic),0.7306,0.4854,-0.2452,0.4175,0.6472,0.2298,0.5313,0.5548,0.0234,False,False

Cycle converged: False
Stop reason: MAX_ITERATIONS_REACHED
The latest-candidate and trajectory metrics can be discussed as diagnostic evidence of the loop, but they must not be labelled as a converged final feedback result.

## 13. Export evaluation tables

All paper-aligned metrics and the additional feedback-loop diagnostics are exported as CSV/JSON files for thesis tables and plots.

In [28]:

trajectory_path = EVALUATION_DIR / "paper_aligned_iteration_trajectory.csv"
diagnostics_path = EVALUATION_DIR / "cycle_evaluator_diagnostics.csv"
consistency_path = EVALUATION_DIR / "external_vs_embedded_consistency.csv"
comparison_path = EVALUATION_DIR / "paper_aligned_baseline_vs_cycle_states.csv"
best_path = EVALUATION_DIR / "paper_aligned_best_observed_iteration.csv"
cardinality_path = EVALUATION_DIR / "goal_cardinality_and_proliferation.csv"
matching_details_path = EVALUATION_DIR / "hungarian_matching_details.csv"
matching_summary_path = EVALUATION_DIR / "hungarian_matching_summary.csv"
matching_issues_path = EVALUATION_DIR / "hungarian_matching_issues.csv"
reference_trajectory_path = EVALUATION_DIR / "ground_truth_goal_similarity_trajectory.csv"
recovery_summary_path = EVALUATION_DIR / "ground_truth_recovery_summary.csv"
duplicate_summary_path = EVALUATION_DIR / "semantic_duplicate_summary.csv"
duplicate_pairs_path = EVALUATION_DIR / "semantic_duplicate_pairs.csv"
actor_feedback_path = EVALUATION_DIR / "actor_branch_feedback_diagnostics.csv"
status_path = EVALUATION_DIR / "paper_aligned_cycle_status.json"

trajectory_df.to_csv(trajectory_path, index=False)
diagnostics_df.to_csv(diagnostics_path, index=False)
consistency_df.to_csv(consistency_path, index=False)
comparison_df.to_csv(comparison_path, index=False)
best_observed_df.to_csv(best_path, index=False)
cardinality_df.to_csv(cardinality_path, index=False)
matching_details_df.to_csv(matching_details_path, index=False)
matching_summary_df.to_csv(matching_summary_path, index=False)
matching_issues_df.to_csv(matching_issues_path, index=False)
reference_goal_trajectory_df.to_csv(reference_trajectory_path, index=False)
recovery_summary_df.to_csv(recovery_summary_path, index=False)
duplicate_summary_df.to_csv(duplicate_summary_path, index=False)
duplicate_pairs_df.to_csv(duplicate_pairs_path, index=False)
actor_feedback_df.to_csv(actor_feedback_path, index=False)

with status_path.open("w", encoding="utf-8") as f:
    json.dump(
        {
            "run": str(RUN_PATH),
            "converged": bool(cycle.get("converged")),
            "stop_reason": cycle.get("stop_reason"),
            "completed_iterations": cycle.get("completed_iterations", len(iterations)),
            "returned_hlg_count": len(RETURNED_HLG),
            "returned_llg_count": len(RETURNED_LLG),
            "latest_candidate_hlg_count": len(LAST_CANDIDATE_HLG),
            "latest_candidate_llg_count": len(LAST_CANDIDATE_LLG),
            "weak_match_threshold_diagnostic": WEAK_MATCH_THRESHOLD,
            "material_similarity_delta_diagnostic": MATERIAL_SIMILARITY_DELTA,
            "semantic_duplicate_threshold_diagnostic": SEMANTIC_DUPLICATE_THRESHOLD,
            "external_global_evaluation_files": {str(i): str(p) for i, p in GLOBAL_EVAL_FILES.items()},
            "external_documentation_coverage_files": {str(i): str(p) for i, p in DOC_COVERAGE_FILES.items()},
        },
        f,
        ensure_ascii=False,
        indent=2,
    )

for p in (
    trajectory_path,
    diagnostics_path,
    consistency_path,
    comparison_path,
    best_path,
    cardinality_path,
    matching_details_path,
    matching_summary_path,
    matching_issues_path,
    reference_trajectory_path,
    recovery_summary_path,
    duplicate_summary_path,
    duplicate_pairs_path,
    actor_feedback_path,
    status_path,
):
    print("Saved:", p)

Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\paper_aligned_iteration_trajectory.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\cycle_evaluator_diagnostics.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\external_vs_embedded_consistency.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\paper_aligned_baseline_vs_cycle_states.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\paper_aligned_best_observed_iteration.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\goal_cardinality_and_proliferation.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\hungarian_matching_details.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\hungarian_matching_summary.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\hungarian_matching_issues.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\ground_truth_goal_similarity_trajectory.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\ground_truth_recovery_summary.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\semantic_duplicate_summary.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\semantic_duplicate_pairs.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\actor_branch_feedback_diagnostics.csv
Saved: C:\Users\agnes_lryeu3v\Desktop\tesi\output\evaluation\SIA Project 25 26_FEW_SHOT_noLlama\paper_aligned_cycle_status.json